---
- name: Install Python, Flask, and Redis
  hosts: all
  become: yes
  tasks:
    - name: Install Python
      apt:
        name: python3
        state: present

    - name: Install pip for Python
      apt:
        name: python3-pip
        state: present

    - name: Install Flask
      pip:
        name: Flask
        executable: pip3
        state: present

    - name: Install Redis server
      apt:
        name: redis-server
        state: present

    - name: Ensure Redis service is running
      service:
        name: redis-server
        state: started
        enabled: yes
